version: '3'

services:
  vuutr:
    build: .
    container_name: vuutr
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/app      
    environment:
      SOCKET_HOST: "http://localhost"
      SOCKET_PORT: 80
      
    # networks:
    #   - database

#   vuutr-database:
#     restart: unless-stopped
#     container_name: vuutr-database
#     image: postgres:9.6-alpine
#     networks:
#       - database

# networks:
#   database:
#     driver: bridge