version: '3'

services:
  vuutr:
    build: .
    container_name: vuutr
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/app      
    environment:
      SOCKET_HOST: "http://localhost"
      SOCKET_PORT: 80
      
    networks:
      - database

  vuutr-database:
    restart: unless-stopped
    container_name: vuutr-database
    image: postgres:9.6-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: teste123
      POSTGRES_USER: root
      POSTGRES_DB: vuutr
    networks:
      - database

networks:
  database:
    driver: bridge